name: Deploy to S3
on:
  push:
    branches:
      - main # Replace 'prod' with the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn

      - name: Build the React app
        run: npm run build

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired AWS region

      - name: Deploy to S3
        run: aws s3 sync ./dist s3://mahadevfurniture.awsaiapp.com/ --delete

      - name: CloudFront Invalidation
        run: aws cloudfront create-invalidation --distribution-id E1PJIRCHLP73TE --paths "/*"